/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.InventoryMenu;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class InventoryMenuView extends javax.swing.JPanel {

    /**
     * Creates new form InventoryMenuView
     */
    public InventoryMenuView() {
        initComponents();
    }

    public JLabel getJlProductsList() {
        return jlProductsList;
    }

    public JLabel getJlRegisterProduct() {
        return jlRegisterProduct;
    }

    public JLabel getJlAssetsRegistration() {
        return jlAssetsRegistration;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jlRegisterProduct = new javax.swing.JLabel();
        jlRegister = new javax.swing.JLabel();
        jlProductsList = new javax.swing.JLabel();
        jlList = new javax.swing.JLabel();
        jlAssetsRegistration = new javax.swing.JLabel();
        jlList1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jlTitle.setFont(new java.awt.Font("Leelawadee UI", 1, 26)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(79, 84, 110));
        jlTitle.setText("Menú del inventario");

        jlRegisterProduct.setSize(new Dimension(153, 152));
        jlRegisterProduct.setMaximumSize(new java.awt.Dimension(153, 152));
        jlRegisterProduct.setMinimumSize(new java.awt.Dimension(153, 152));
        jlRegisterProduct.setPreferredSize(new java.awt.Dimension(153, 152));
        ImageIcon img = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Registro de Productos.png"));
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(jlRegisterProduct.getWidth(), jlRegisterProduct.getHeight(), Image.SCALE_SMOOTH));
        jlRegisterProduct.setIcon(icon);

        jlRegister.setBackground(new java.awt.Color(79, 84, 110));
        jlRegister.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jlRegister.setForeground(new java.awt.Color(79, 84, 110));
        jlRegister.setText("Registro de productos");

        jlProductsList.setSize(new Dimension(153, 152));
        jlProductsList.setMaximumSize(new java.awt.Dimension(153, 152));
        jlProductsList.setMinimumSize(new java.awt.Dimension(153, 152));
        jlProductsList.setPreferredSize(new java.awt.Dimension(153, 152));
        ImageIcon img1 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Lista de Productos.png"));
        Icon icon1 = new ImageIcon(img1.getImage().getScaledInstance(jlProductsList.getWidth(), jlProductsList.getHeight(), Image.SCALE_SMOOTH));
        jlProductsList.setIcon(icon1);

        jlList.setBackground(new java.awt.Color(79, 84, 110));
        jlList.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jlList.setForeground(new java.awt.Color(79, 84, 110));
        jlList.setText("Lista de productos");

        jlAssetsRegistration.setSize(new Dimension(153, 152));
        jlAssetsRegistration.setMaximumSize(new java.awt.Dimension(153, 152));
        jlAssetsRegistration.setMinimumSize(new java.awt.Dimension(153, 152));
        jlAssetsRegistration.setPreferredSize(new java.awt.Dimension(153, 152));
        ImageIcon img2 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Registro Activos.png"));
        Icon icon2 = new ImageIcon(img2.getImage().getScaledInstance(jlAssetsRegistration.getWidth(), jlAssetsRegistration.getHeight(), Image.SCALE_SMOOTH));
        jlAssetsRegistration.setIcon(icon2);

        jlList1.setBackground(new java.awt.Color(79, 84, 110));
        jlList1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jlList1.setForeground(new java.awt.Color(79, 84, 110));
        jlList1.setText("Registro de activos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jlTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlRegisterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlRegister))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlList)
                            .addComponent(jlProductsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlList1)
                            .addComponent(jlAssetsRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jlTitle)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlRegisterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlProductsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlList)))
                .addGap(47, 47, 47)
                .addComponent(jlAssetsRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlList1)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAssetsRegistration;
    private javax.swing.JLabel jlList;
    private javax.swing.JLabel jlList1;
    private javax.swing.JLabel jlProductsList;
    private javax.swing.JLabel jlRegister;
    private javax.swing.JLabel jlRegisterProduct;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables
}
