/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.MainMenu;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import lib.models.User;


/**
 *
 * @author user
 */
public class MainMenuView extends javax.swing.JPanel {
    
    private User user;
    
    /**
     * Creates new form MainMenuView
     */
    public MainMenuView(User user) throws SQLException {
        this.user = user;
        initComponents();
        
        fillInfo();
    }
    
    private void fillInfo() throws SQLException{
        jlNameUser.setText(user.getName());
        jlEmailUser.setText(user.getEmail());
        jlRangeUser.setText(user.getRange());
        jlIdUser.setText(Integer.toString(user.getIdCard()));
        
        this.repaint();
        
        JPanel listPanel = new JPanel();
        listPanel.setBackground(Color.WHITE);
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        
        MainMenuModel model = new MainMenuModel();
        ArrayList<DateAlertPanel> dateAlerts = model.fillDatePanels();
        ArrayList<QuantityAlertPanel> quantityAlerts = model.fillQuantityPanels();
        
        for(DateAlertPanel panel : dateAlerts){
            listPanel.add(panel);
            panel.setVisible(true);
        }
        System.out.println(jScrollAlerts.getComponentCount());
        
        for(QuantityAlertPanel panel : quantityAlerts){
            listPanel.add(panel);
            panel.setVisible(true);
        }
        System.out.println(listPanel.getComponentCount());
        
        jScrollAlerts.setBackground(new Color(255, 255, 255));
        jScrollAlerts.setViewportView(listPanel);
        jScrollAlerts.updateUI();
    }

    public JLabel getJlImage() {
        return jlImage;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlUserImage = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlRange = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlId = new javax.swing.JLabel();
        jlNameUser = new javax.swing.JLabel();
        jlRangeUser = new javax.swing.JLabel();
        jlEmailUser = new javax.swing.JLabel();
        jlIdUser = new javax.swing.JLabel();
        jlEdit = new javax.swing.JLabel();
        jScrollAlerts = new javax.swing.JScrollPane();
        jlImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1085, 728));

        jlTitle.setFont(new java.awt.Font("Leelawadee UI", 1, 42)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(79, 84, 110));
        jlTitle.setText("Bienvenido a Primal Enterprise");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlUserImage.setSize(new Dimension(79, 79));
        jlUserImage.setMaximumSize(new java.awt.Dimension(79, 79));
        jlUserImage.setMinimumSize(new java.awt.Dimension(79, 79));
        jlUserImage.setPreferredSize(new java.awt.Dimension(79, 79));
        ImageIcon img2 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Usuario.png"));
        Icon icon2 = new ImageIcon(img2.getImage().getScaledInstance(jlUserImage.getWidth(), jlUserImage.getHeight(), Image.SCALE_SMOOTH));
        jlUserImage.setIcon(icon2);

        jlName.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlName.setForeground(new java.awt.Color(79, 84, 110));
        jlName.setText("Nombre: ");

        jlRange.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlRange.setForeground(new java.awt.Color(79, 84, 110));
        jlRange.setText("Rango:");

        jlEmail.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(79, 84, 110));
        jlEmail.setText("Correo Electrónico:");

        jlId.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlId.setForeground(new java.awt.Color(79, 84, 110));
        jlId.setText("Id:");

        jlNameUser.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlNameUser.setForeground(new java.awt.Color(79, 84, 110));
        jlNameUser.setText("nombre usuario");

        jlRangeUser.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlRangeUser.setForeground(new java.awt.Color(79, 84, 110));
        jlRangeUser.setText("rango usuario");

        jlEmailUser.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlEmailUser.setForeground(new java.awt.Color(79, 84, 110));
        jlEmailUser.setText("email usuario");

        jlIdUser.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlIdUser.setForeground(new java.awt.Color(79, 84, 110));
        jlIdUser.setText("id usuario");

        jlEdit.setSize(new Dimension(39, 39));
        jlEdit.setMaximumSize(new java.awt.Dimension(39, 39));
        jlEdit.setMinimumSize(new java.awt.Dimension(39, 39));
        jlEdit.setPreferredSize(new java.awt.Dimension(39, 39));
        ImageIcon img3 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Editar.png"));
        Icon icon3 = new ImageIcon(img3.getImage().getScaledInstance(jlEdit.getWidth(), jlEdit.getHeight(), Image.SCALE_SMOOTH));
        jlEdit.setIcon(icon3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlEmailUser))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlIdUser)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNameUser))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlRange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlRangeUser)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlName)
                            .addComponent(jlNameUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRange)
                            .addComponent(jlRangeUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEmail)
                            .addComponent(jlEmailUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlId)
                            .addComponent(jlIdUser))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollAlerts.setBackground(new java.awt.Color(255, 255, 255));

        jlImage.setSize(new Dimension(934, 393));
        jlImage.setMaximumSize(new java.awt.Dimension(934, 393));
        jlImage.setMinimumSize(new java.awt.Dimension(934, 393));
        jlImage.setPreferredSize(new java.awt.Dimension(934, 393));
        ImageIcon img1 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Imagen Lobby.jpg"));
        Icon icon1 = new ImageIcon(img1.getImage().getScaledInstance(jlImage.getWidth(), jlImage.getHeight(), Image.SCALE_SMOOTH));
        jlImage.setIcon(icon1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitle)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollAlerts, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollAlerts, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollAlerts;
    public javax.swing.JLabel jlEdit;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEmailUser;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlIdUser;
    public javax.swing.JLabel jlImage;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlNameUser;
    private javax.swing.JLabel jlRange;
    private javax.swing.JLabel jlRangeUser;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlUserImage;
    // End of variables declaration//GEN-END:variables
}
