/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.MainMenu;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import lib.models.Product;

/**
 *
 * @author user
 */
public class QuantityAlertPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form QuantityAlertPanel
     */
    public QuantityAlertPanel(String name, int id, int quantity, String icon) {
        
        initComponents();
        
        /*jlAlertIcon.setSize(new Dimension(50, 50));
        jlIcon.setSize(new Dimension(62, 62));*/
        
        /*ImageIcon img2 = new ImageIcon(getClass().getResource("/documentation/Imagenes/" + icon));
        Icon icon2 = new ImageIcon(img2.getImage().getScaledInstance(jlIcon.getWidth(), jlIcon.getHeight(), Image.SCALE_SMOOTH));
        jlIcon.setIcon(icon2);*/
        
        jlName.setText(name);
        jlId.setText(Integer.toString(id));
        jlQuantity.setText(Integer.toString(quantity));
        
    }

    public JLabel getJlId() {
        return jlId;
    }

    public JLabel getJlName() {
        return jlName;
    }

    public JLabel getJlQuantity() {
        return jlQuantity;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jlIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlAlertIcon = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlQuantity = new javax.swing.JLabel();
        jlId = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(340, 80));

        jlIcon.setSize(new Dimension(62, 62));
        jlIcon.setMaximumSize(new java.awt.Dimension(62, 62));
        jlIcon.setMinimumSize(new java.awt.Dimension(62, 62));
        jlIcon.setPreferredSize(new java.awt.Dimension(62, 62));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 84, 110));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 84, 110));
        jLabel2.setText("Cantidad:");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 84, 110));
        jLabel3.setText("Id:");

        jlAlertIcon.setSize(new Dimension(50, 50));
        jlAlertIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        jlAlertIcon.setMinimumSize(new java.awt.Dimension(50, 50));
        jlAlertIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        ImageIcon img1 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Advertencia.png"));
        Icon icon1 = new ImageIcon(img1.getImage().getScaledInstance(jlAlertIcon.getWidth(), jlAlertIcon.getHeight(), Image.SCALE_SMOOTH));
        jlAlertIcon.setIcon(icon1);

        jlName.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlName.setForeground(new java.awt.Color(79, 84, 110));
        jlName.setText("nombre producto");

        jlQuantity.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlQuantity.setForeground(new java.awt.Color(79, 84, 110));
        jlQuantity.setText("cantidad producto");

        jlId.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jlId.setForeground(new java.awt.Color(79, 84, 110));
        jlId.setText("cantidad producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jlAlertIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlName))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlQuantity))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlAlertIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlAlertIcon;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlQuantity;
    // End of variables declaration//GEN-END:variables
}
