/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.registroProd;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import lib.utils.AppColors;

/**
 *
 * @author Fredy AGP
 */
public class registroProd extends javax.swing.JPanel {
private AppColors color = new AppColors();
    /**
     * Creates new form registroProd
     */
    public registroProd() {
        initComponents();
    }

    public JLabel getRegistrarB() {
        return registrarB;
    }

    public JLabel getRegresarB() {
        return regresarB;
    }

    public JTextField getCantidadTF() {
        return cantidadTF;
    }

    public JTextField getDescripcionTF() {
        return descripcionTF;
    }

    public JTextField getLugarTF() {
        return lugarTF;
    }

    public JTextField getMarcaTF() {
        return marcaTF;
    }

    public JTextField getNitTF() {
        return nitTF;
    }

    public JTextField getNombreTF() {
        return nombreTF;
    }

    public JTextField getTipolTF() {
        return tipolTF;
    }

    public JTextField getAlmacenamientoTF() {
        return almacenamientoTF;
    }

    public JComboBox<String> getAnoCB() {
        return anoCB;
    }

    public JComboBox<String> getDiaCB() {
        return diaCB;
    }

    public JComboBox<String> getMesCB() {
        return mesCB;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descripcionTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidadTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        almacenamientoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lugarTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipolTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        regresarB = new javax.swing.JLabel();
        marcaTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nitTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        registrarB = new javax.swing.JLabel();
        anoCB = new javax.swing.JComboBox<>();
        diaCB = new javax.swing.JComboBox<>();
        mesCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        descripcionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel5.setForeground(color.textColor());
        jLabel5.setText("Nit Proveedor:");

        cantidadTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel6.setForeground(color.textColor());
        jLabel6.setText("Cantidad:");

        almacenamientoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenamientoTFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel7.setForeground(color.textColor());
        jLabel7.setText("Metodo Almacenamiento");

        lugarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarTFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel8.setForeground(color.textColor());
        jLabel8.setText("Descripción:");

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel9.setForeground(color.textColor());
        jLabel9.setText("Lugar de Almacenamiento:");

        tipolTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipolTFActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel10.setForeground(color.textColor());
        jLabel10.setText("Registro de Productos");

        regresarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/Boton de Atras(2).png"))); // NOI18N

        marcaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel2.setForeground(color.textColor());
        jLabel2.setText("Nombre:");

        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel3.setForeground(color.textColor());
        jLabel3.setText("Marca:");

        nitTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel4.setForeground(color.textColor());
        jLabel4.setText("Tipo:");

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel11.setForeground(color.textColor());
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/Icono Calendario.png"))); // NOI18N
        jLabel11.setText("Fecha de Vencimiento");

        registrarB.setBackground(color.buttonColor());
        registrarB.setFont(new java.awt.Font("Leelawadee UI", 0, 32)); // NOI18N
        registrarB.setForeground(new java.awt.Color(255, 255, 255));
        registrarB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarB.setText("Registrar");
        registrarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarB.setOpaque(true);

        anoCB.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        anoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));

        diaCB.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        diaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesCB.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        mesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel1.setText("Año");

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel12.setText("Mes");

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jLabel13.setText("Dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regresarB)
                .addGap(258, 258, 258)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipolTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(197, 197, 197)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(almacenamientoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(descripcionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lugarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(diaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel12)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel13)
                                .addGap(14, 14, 14))
                            .addComponent(registrarB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regresarB)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(anoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(registrarB)))
                        .addGap(312, 312, 312))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tipolTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(nitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(almacenamientoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lugarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(descripcionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionTFActionPerformed

    private void cantidadTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTFActionPerformed

    private void almacenamientoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenamientoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almacenamientoTFActionPerformed

    private void lugarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarTFActionPerformed

    private void tipolTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipolTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipolTFActionPerformed

    private void marcaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTFActionPerformed

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void nitTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almacenamientoTF;
    private javax.swing.JComboBox<String> anoCB;
    private javax.swing.JTextField cantidadTF;
    private javax.swing.JTextField descripcionTF;
    private javax.swing.JComboBox<String> diaCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lugarTF;
    private javax.swing.JTextField marcaTF;
    private javax.swing.JComboBox<String> mesCB;
    private javax.swing.JTextField nitTF;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel registrarB;
    private javax.swing.JLabel regresarB;
    private javax.swing.JTextField tipolTF;
    // End of variables declaration//GEN-END:variables
}
