//Java imports
package lib.ui.productionSubmenu;

import javax.swing.JLabel;
import lib.utils.AppColors;

public class ProductionSubmenuView extends javax.swing.JPanel {
    private AppColors colors = new AppColors();

    public ProductionSubmenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        RegisterProductionsButton = new javax.swing.JLabel();
        RegisterProductionsLabel = new javax.swing.JLabel();
        ProductionsListButton = new javax.swing.JLabel();
        ProductionsListLabel = new javax.swing.JLabel();
        RegisterProductButton = new javax.swing.JLabel();
        RegisterProductLabel = new javax.swing.JLabel();
        ProductListButton = new javax.swing.JLabel();
        ProductListLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(this.colors.borderColor()));

        Title.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        Title.setForeground(this.colors.textColor());
        Title.setText("Productos e Insumos");

        RegisterProductionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/RegisterProductionIcon_200x200Px.png"))); // NOI18N
        RegisterProductionsButton.setBorder(javax.swing.BorderFactory.createLineBorder(this.colors.borderColor()));

        RegisterProductionsLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        RegisterProductionsLabel.setForeground(this.colors.textColor());
        RegisterProductionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterProductionsLabel.setText("Registro de Productos");

        ProductionsListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/ProductionsList_200x200Px.png"))); // NOI18N
        ProductionsListButton.setBorder(javax.swing.BorderFactory.createLineBorder(this.colors.borderColor()));

        ProductionsListLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        ProductionsListLabel.setForeground(this.colors.textColor());
        ProductionsListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductionsListLabel.setText("Registro de Insumos");

        RegisterProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/RegisterProductIcon_200x200Px.png"))); // NOI18N
        RegisterProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(this.colors.borderColor()));

        RegisterProductLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        RegisterProductLabel.setForeground(this.colors.textColor());
        RegisterProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterProductLabel.setText("Lista de Productos");

        ProductListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/productsList_200x200Px.png"))); // NOI18N
        ProductListButton.setBorder(javax.swing.BorderFactory.createLineBorder(this.colors.borderColor()));

        ProductListLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        ProductListLabel.setForeground(this.colors.textColor());
        ProductListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductListLabel.setText("Lista de Insumos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegisterProductionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(RegisterProductionsButton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RegisterProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ProductionsListButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductListButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProductionsListLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductListLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterProductButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(260, 260, 260))
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterProductionsButton)
                    .addComponent(RegisterProductButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductionsListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterProductionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProductListButton)
                    .addComponent(ProductionsListButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getRegisterProductionsButton() {return this.RegisterProductionsButton;}
    public JLabel getRegisterProductButton() {return this.RegisterProductButton;}
    public JLabel getProductionsListButton() {return this.ProductionsListButton;}
    public JLabel getProductListButton() {return this.ProductListButton;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProductListButton;
    private javax.swing.JLabel ProductListLabel;
    private javax.swing.JLabel ProductionsListButton;
    private javax.swing.JLabel ProductionsListLabel;
    private javax.swing.JLabel RegisterProductButton;
    private javax.swing.JLabel RegisterProductLabel;
    private javax.swing.JLabel RegisterProductionsButton;
    private javax.swing.JLabel RegisterProductionsLabel;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
