/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.consultProductView;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author rodri
 */
public class ConsultProductView extends javax.swing.JPanel {

    /**
     * Creates new form ConsultProductView
     */
    public ConsultProductView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoProductolb = new javax.swing.JLabel();
        userAdministrationTittle1 = new javax.swing.JLabel();
        nombrelb = new javax.swing.JLabel();
        tipolb = new javax.swing.JLabel();
        cantidadlb = new javax.swing.JLabel();
        lugarAlmacenamientolb = new javax.swing.JLabel();
        caducidadlb = new javax.swing.JLabel();
        descripcionlb = new javax.swing.JLabel();
        atraslb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaDescripcion = new javax.swing.JTextArea();
        jtxtName = new javax.swing.JTextField();
        jtxtAmount = new javax.swing.JTextField();
        jtxtType = new javax.swing.JTextField();
        jtxtPlace = new javax.swing.JTextField();
        lugarAlmacenamientolb1 = new javax.swing.JLabel();
        jtxtMethod = new javax.swing.JTextField();
        jcbxYear = new javax.swing.JComboBox<>();
        jcbxMonth = new javax.swing.JComboBox<>();
        jcbxDay = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jlSave = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1060, 708));
        setMinimumSize(new java.awt.Dimension(1060, 708));
        setPreferredSize(new java.awt.Dimension(1060, 708));

        iconoProductolb.setText("jLabel1");
        iconoProductolb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        userAdministrationTittle1.setBackground(new java.awt.Color(79, 84, 110));
        userAdministrationTittle1.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        userAdministrationTittle1.setForeground(new java.awt.Color(79, 84, 110));
        userAdministrationTittle1.setText("Lista de Productos");

        nombrelb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nombrelb.setText("Nombre : ");

        tipolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        tipolb.setText("Tipo : ");

        cantidadlb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cantidadlb.setText("Cantidad : ");

        lugarAlmacenamientolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        lugarAlmacenamientolb.setText("Lugar almacenamiento : ");

        caducidadlb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        caducidadlb.setText("Fecha Caducidad :");

        descripcionlb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        descripcionlb.setText("Descripción :");

        atraslb.setSize(new Dimension(66,69));
        atraslb.setText("jLabel1");
        atraslb.setMaximumSize(new java.awt.Dimension(66, 69));
        atraslb.setMinimumSize(new java.awt.Dimension(66, 69));
        ImageIcon backButton = new ImageIcon(getClass().getResource("/documentation/Images/Boton de Atras.png"));
        Icon fondo3 = new ImageIcon(backButton .getImage().getScaledInstance(atraslb.getWidth(),atraslb.getHeight(),Image.SCALE_SMOOTH));
        atraslb.setIcon(fondo3);
        atraslb.setPreferredSize(new java.awt.Dimension(66, 69));

        jtxtaDescripcion.setEditable(false);
        jtxtaDescripcion.setColumns(20);
        jtxtaDescripcion.setFont(new java.awt.Font("Leelawadee UI", 0, 15)); // NOI18N
        jtxtaDescripcion.setLineWrap(true);
        jtxtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtxtaDescripcion);

        jtxtName.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jtxtAmount.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jtxtType.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jtxtPlace.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        lugarAlmacenamientolb1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        lugarAlmacenamientolb1.setText("Método almacenamiento : ");

        jtxtMethod.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N

        jcbxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jcbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jcbxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jPanel3.setBackground(new java.awt.Color(20, 56, 197));

        jlSave.setFont(new java.awt.Font("Leelawadee UI", 0, 22)); // NOI18N
        jlSave.setForeground(new java.awt.Color(255, 255, 255));
        jlSave.setText("            Guardar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSave, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSave, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(iconoProductolb, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cantidadlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descripcionlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caducidadlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrelb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipolb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtType, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lugarAlmacenamientolb1)
                            .addComponent(lugarAlmacenamientolb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(atraslb, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userAdministrationTittle1)
                .addGap(352, 352, 352))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atraslb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userAdministrationTittle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombrelb)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipolb)
                            .addComponent(jtxtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadlb)
                            .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lugarAlmacenamientolb)
                            .addComponent(jtxtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lugarAlmacenamientolb1)
                            .addComponent(jtxtMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcionlb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caducidadlb)
                            .addComponent(jcbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconoProductolb, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atraslb;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JLabel caducidadlb;
    private javax.swing.JLabel cantidadlb;
    private javax.swing.JLabel descripcionlb;
    private javax.swing.JLabel iconoProductolb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbxDay;
    private javax.swing.JComboBox<String> jcbxMonth;
    private javax.swing.JComboBox<String> jcbxYear;
    private javax.swing.JLabel jlSave;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtMethod;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPlace;
    private javax.swing.JTextField jtxtType;
    private javax.swing.JTextArea jtxtaDescripcion;
    private javax.swing.JLabel lugarAlmacenamientolb;
    private javax.swing.JLabel lugarAlmacenamientolb1;
    private javax.swing.JLabel nombrelb;
    private javax.swing.JLabel tipolb;
    private javax.swing.JLabel userAdministrationTittle1;
    // End of variables declaration//GEN-END:variables

    public JLabel getAtraslb() {
        return atraslb;
    }

    public JLabel getJlSave() {
        return jlSave;
    }



    public JComboBox<String> getJcbxDay() {
        return jcbxDay;
    }

    public JComboBox<String> getJcbxMonth() {
        return jcbxMonth;
    }

    public JComboBox<String> getJcbxYear() {
        return jcbxYear;
    }

    public JTextField getJtxtAmount() {
        return jtxtAmount;
    }

    public JTextField getJtxtMethod() {
        return jtxtMethod;
    }

    public JTextField getJtxtName() {
        return jtxtName;
    }

    public JTextField getJtxtPlace() {
        return jtxtPlace;
    }

    public JTextField getJtxtType() {
        return jtxtType;
    }

    public JTextArea getJtxtaDescripcion() {
        return jtxtaDescripcion;
    }

    

    
}
