/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.consultProductView;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;

/**
 *
 * @author rodri
 */
public class ConsultProductView extends javax.swing.JPanel {

    /**
     * Creates new form ConsultProductView
     */
    public ConsultProductView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoProductolb = new javax.swing.JLabel();
        userAdministrationTittle1 = new javax.swing.JLabel();
        nombrelb = new javax.swing.JLabel();
        tipolb = new javax.swing.JLabel();
        cantidadlb = new javax.swing.JLabel();
        lugarAlmacenamientolb = new javax.swing.JLabel();
        caducidadlb = new javax.swing.JLabel();
        descripcionlb = new javax.swing.JLabel();
        nombreInfolb = new javax.swing.JLabel();
        tipoInfolb = new javax.swing.JLabel();
        cantidadInfolb = new javax.swing.JLabel();
        almacenamientoInfolb = new javax.swing.JLabel();
        fechaCaducidadInfolb = new javax.swing.JLabel();
        atraslb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaDescripcion = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1060, 708));
        setMinimumSize(new java.awt.Dimension(1060, 708));
        setPreferredSize(new java.awt.Dimension(1060, 708));

        iconoProductolb.setText("jLabel1");
        iconoProductolb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        userAdministrationTittle1.setBackground(new java.awt.Color(79, 84, 110));
        userAdministrationTittle1.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        userAdministrationTittle1.setForeground(new java.awt.Color(79, 84, 110));
        userAdministrationTittle1.setText("Lista de Productos");

        nombrelb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nombrelb.setText("Nombre : ");

        tipolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        tipolb.setText("Tipo : ");

        cantidadlb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cantidadlb.setText("Cantidad : ");

        lugarAlmacenamientolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        lugarAlmacenamientolb.setText("Lugar almacenamiento : ");

        caducidadlb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        caducidadlb.setText("Fecha Caducidad :");

        descripcionlb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        descripcionlb.setText("Descripción :");

        nombreInfolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        nombreInfolb.setText("jLabel1");

        tipoInfolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        tipoInfolb.setText("jLabel1");

        cantidadInfolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        cantidadInfolb.setText("jLabel1");

        almacenamientoInfolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        almacenamientoInfolb.setText("jLabel1");

        fechaCaducidadInfolb.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        fechaCaducidadInfolb.setText("jLabel1");

        atraslb.setSize(new Dimension(66,69));
        atraslb.setText("jLabel1");
        atraslb.setMaximumSize(new java.awt.Dimension(66, 69));
        atraslb.setMinimumSize(new java.awt.Dimension(66, 69));
        ImageIcon backButton = new ImageIcon(getClass().getResource("/documentation/Images/Boton de Atras.png"));
        Icon fondo3 = new ImageIcon(backButton .getImage().getScaledInstance(atraslb.getWidth(),atraslb.getHeight(),Image.SCALE_SMOOTH));
        atraslb.setIcon(fondo3);
        atraslb.setPreferredSize(new java.awt.Dimension(66, 69));

        jtxtaDescripcion.setEditable(false);
        jtxtaDescripcion.setColumns(20);
        jtxtaDescripcion.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jtxtaDescripcion.setLineWrap(true);
        jtxtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtxtaDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(iconoProductolb, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombrelb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreInfolb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipolb)
                        .addGap(18, 18, 18)
                        .addComponent(tipoInfolb, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cantidadlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadInfolb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lugarAlmacenamientolb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(almacenamientoInfolb, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descripcionlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caducidadlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaCaducidadInfolb, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(atraslb, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userAdministrationTittle1)
                .addGap(352, 352, 352))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atraslb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userAdministrationTittle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombrelb)
                            .addComponent(nombreInfolb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipolb)
                            .addComponent(tipoInfolb))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadlb)
                            .addComponent(cantidadInfolb))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lugarAlmacenamientolb)
                            .addComponent(almacenamientoInfolb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcionlb)))
                    .addComponent(iconoProductolb, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caducidadlb)
                    .addComponent(fechaCaducidadInfolb))
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel almacenamientoInfolb;
    private javax.swing.JLabel atraslb;
    private javax.swing.JLabel caducidadlb;
    private javax.swing.JLabel cantidadInfolb;
    private javax.swing.JLabel cantidadlb;
    private javax.swing.JLabel descripcionlb;
    private javax.swing.JLabel fechaCaducidadInfolb;
    private javax.swing.JLabel iconoProductolb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtxtaDescripcion;
    private javax.swing.JLabel lugarAlmacenamientolb;
    private javax.swing.JLabel nombreInfolb;
    private javax.swing.JLabel nombrelb;
    private javax.swing.JLabel tipoInfolb;
    private javax.swing.JLabel tipolb;
    private javax.swing.JLabel userAdministrationTittle1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getNombreInfolb() {
        return nombreInfolb;
    }

    public javax.swing.JLabel getTipoInfolb() {
        return tipoInfolb;
    }

    public javax.swing.JLabel getCantidadInfolb() {
        return cantidadInfolb;
    }

    public javax.swing.JLabel getAlmacenamientoInfolb() {
        return almacenamientoInfolb;
    }

    public javax.swing.JLabel getLugarAlmacenamientolb() {
        return lugarAlmacenamientolb;
    }

    public JTextArea getJtxtaDescripcion() {
        return jtxtaDescripcion;
    }

    

    public javax.swing.JLabel getFechaCaducidadInfolb() {
        return fechaCaducidadInfolb;
    }

    public javax.swing.JLabel getAtraslb() {
        return atraslb;
    }

    
}
