//Java imports
package lib.ui.buttonBar;

import javax.swing.JLabel;
import lib.models.User;
import lib.utils.AppColors;

public class ButtonBarView extends javax.swing.JPanel {
    private final AppColors color = new AppColors();

    public ButtonBarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsTitle = new javax.swing.JLabel();
        homeButton = new javax.swing.JLabel();
        inventoryButton = new javax.swing.JLabel();
        productionButton = new javax.swing.JLabel();
        buttonsTitle_2 = new javax.swing.JLabel();
        usersButton = new javax.swing.JLabel();
        activesButton = new javax.swing.JLabel();
        reportsButton = new javax.swing.JLabel();

        setBackground(this.color.menuBotonesColor());

        buttonsTitle.setFont(new java.awt.Font("Leelawadee UI", 0, 28)); // NOI18N
        buttonsTitle.setForeground(new java.awt.Color(255, 255, 255));
        buttonsTitle.setText("Menu Principal");

        homeButton.setBackground(this.color.menuBotones_botonColor());
        homeButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        homeButton.setForeground(this.color.menuBotonesColor());
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/HomeIcon_65x60Px.png"))); // NOI18N
        homeButton.setText("  Pagina Principal");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setOpaque(true);

        inventoryButton.setBackground(this.color.menuBotones_botonColor());
        inventoryButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        inventoryButton.setForeground(this.color.menuBotonesColor());
        inventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/InventoryIcon_65x60Px.png"))); // NOI18N
        inventoryButton.setText("  Inventario");
        inventoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventoryButton.setOpaque(true);

        productionButton.setBackground(this.color.menuBotones_botonColor());
        productionButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        productionButton.setForeground(this.color.menuBotonesColor());
        productionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/ProductionIcon_65x60Px.png"))); // NOI18N
        productionButton.setText("  Producciones");
        productionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productionButton.setOpaque(true);

        buttonsTitle_2.setFont(new java.awt.Font("Leelawadee UI", 0, 28)); // NOI18N
        buttonsTitle_2.setForeground(new java.awt.Color(255, 255, 255));
        buttonsTitle_2.setText("Administración");

        usersButton.setBackground(this.color.menuBotones_botonColor());
        usersButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        usersButton.setForeground(this.color.menuBotonesColor());
        usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/UserIcon_65x60Px.png"))); // NOI18N
        usersButton.setText("  Usuarios");
        usersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersButton.setOpaque(true);

        activesButton.setBackground(this.color.menuBotones_botonColor());
        activesButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        activesButton.setForeground(this.color.menuBotonesColor());
        activesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/ConfigIcon_65x60Px.png"))); // NOI18N
        activesButton.setText("  Activos/Productos");
        activesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activesButton.setOpaque(true);

        reportsButton.setBackground(this.color.menuBotones_botonColor());
        reportsButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        reportsButton.setForeground(this.color.menuBotonesColor());
        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/ReportsIcon_65x65Px.png"))); // NOI18N
        reportsButton.setText("  Informes");
        reportsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportsButton.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(activesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(reportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(buttonsTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(buttonsTitle_2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(buttonsTitle)
                .addGap(18, 18, 18)
                .addComponent(homeButton)
                .addGap(30, 30, 30)
                .addComponent(inventoryButton)
                .addGap(39, 39, 39)
                .addComponent(productionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buttonsTitle_2)
                .addGap(18, 18, 18)
                .addComponent(usersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(activesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents
    protected void setVisibility(User user)
    {
        switch (user.getRange()){
            case "Secretario/a":
                activesButton.setEnabled(false);
                inventoryButton.setEnabled(false);
                productionButton.setEnabled(false);
                usersButton.setEnabled(false);
                reportsButton.setEnabled(true);
                break;
            case "Administrador":
                activesButton.setEnabled(true);
                inventoryButton.setEnabled(true);
                productionButton.setEnabled(true);
                usersButton.setEnabled(true);
                reportsButton.setEnabled(true);
                break;
            case "Administrador de producciones":
                 activesButton.setEnabled(false);
                inventoryButton.setEnabled(false);
                productionButton.setEnabled(true);
                usersButton.setEnabled(false);
                reportsButton.setEnabled(true);
                break;
            case "Administrador de inventario":
                activesButton.setEnabled(false);
                inventoryButton.setEnabled(true);
                productionButton.setEnabled(false);
                usersButton.setEnabled(true);
                reportsButton.setEnabled(false);
                break;
        }
    }
    protected JLabel getHomeButton() {return this.homeButton;}
    protected JLabel getInventoryButton() {return this.inventoryButton;}
    protected JLabel getProductionButton() {return this.productionButton;}
    protected JLabel getUsersButton() {return this.usersButton;}
    protected JLabel getActivesButton() {return this.activesButton;}
    protected JLabel getReportsButton() {return this.reportsButton;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activesButton;
    private javax.swing.JLabel buttonsTitle;
    private javax.swing.JLabel buttonsTitle_2;
    private javax.swing.JLabel homeButton;
    private javax.swing.JLabel inventoryButton;
    private javax.swing.JLabel productionButton;
    private javax.swing.JLabel reportsButton;
    private javax.swing.JLabel usersButton;
    // End of variables declaration//GEN-END:variables

}
