/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.UsersList;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class UsersListView extends javax.swing.JPanel {

    /**
     * Creates new form UsersListView
     */
    public UsersListView() {
        initComponents();
    }

    public JLabel getJlAddUser() {
        return jlAddUser;
    }

    public JTable getJtUsers() {
        return jtUsers;
    }

    public JLabel getJlReturn() {
        return jlReturn;
    }

    public JLabel getJlDeleteUser() {
        return jlDeleteUser;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsers = new javax.swing.JTable();
        jlAddUser = new javax.swing.JLabel();
        jlReturn = new javax.swing.JLabel();
        jlDeleteUser = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jlTitle.setFont(new java.awt.Font("Leelawadee UI", 1, 26)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(79, 84, 110));
        jlTitle.setText("Usuarios registrados");

        jtUsers.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        jtUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Cédula", "Telefono", "Rango", "Email", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtUsers);
        if (jtUsers.getColumnModel().getColumnCount() > 0) {
            jtUsers.getColumnModel().getColumn(0).setResizable(false);
            jtUsers.getColumnModel().getColumn(1).setResizable(false);
            jtUsers.getColumnModel().getColumn(2).setResizable(false);
            jtUsers.getColumnModel().getColumn(3).setResizable(false);
            jtUsers.getColumnModel().getColumn(4).setResizable(false);
            jtUsers.getColumnModel().getColumn(5).setResizable(false);
            jtUsers.getColumnModel().getColumn(6).setResizable(false);
        }

        jlAddUser.setSize(new Dimension(68,68));
        jlAddUser.setMaximumSize(new java.awt.Dimension(68, 68));
        jlAddUser.setMinimumSize(new java.awt.Dimension(68, 68));
        jlAddUser.setPreferredSize(new java.awt.Dimension(68, 68));
        ImageIcon img = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Adicionar.png"));
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(jlAddUser.getWidth(), jlAddUser.getHeight(), Image.SCALE_SMOOTH));
        jlAddUser.setIcon(icon);

        jlReturn.setSize(new Dimension(68,68));
        jlReturn.setMaximumSize(new java.awt.Dimension(68, 68));
        jlReturn.setMinimumSize(new java.awt.Dimension(68, 68));
        jlReturn.setPreferredSize(new java.awt.Dimension(68, 68));
        ImageIcon img2 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Boton de Atras.png"));
        Icon icon2 = new ImageIcon(img2.getImage().getScaledInstance(jlReturn.getWidth(), jlReturn.getHeight(), Image.SCALE_SMOOTH));
        jlReturn.setIcon(icon2);

        jlDeleteUser.setSize(new Dimension(68,68));
        jlDeleteUser.setMaximumSize(new java.awt.Dimension(68, 68));
        jlDeleteUser.setMinimumSize(new java.awt.Dimension(68, 68));
        jlDeleteUser.setPreferredSize(new java.awt.Dimension(68, 68));
        ImageIcon img3 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Eliminar Usuario.png"));
        Icon icon3 = new ImageIcon(img3.getImage().getScaledInstance(jlDeleteUser.getWidth(), jlDeleteUser.getHeight(), Image.SCALE_SMOOTH));
        jlDeleteUser.setIcon(icon3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jlReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327)
                        .addComponent(jlTitle)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jlTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jlAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jlDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAddUser;
    private javax.swing.JLabel jlDeleteUser;
    private javax.swing.JLabel jlReturn;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTable jtUsers;
    // End of variables declaration//GEN-END:variables
}
