/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.Inventory;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class InventoryView extends javax.swing.JPanel {

    /**
     * Creates new form InventoryView
     */
    public InventoryView() {
        initComponents();
        
        
    }

    public JTable getJtInventory() {
        return jtInventory;
    }

    public JLabel getJlAddProduct() {
        return jlAddProduct;
    }

    public JLabel getJlEdit() {
        return jlEdit;
    }

    public JLabel getJlReturn() {
        return jlReturn;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlReturn = new javax.swing.JLabel();
        jlTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventory = new JTable(new DefaultTableModel(new Object[]{"", "Nombre", "Marca", "Tipo", "Fecha de caducidad", "Cantidad"},0));
        jlAddProduct = new javax.swing.JLabel();
        jlEdit = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jlReturn.setSize(new Dimension(68,68));
        jlReturn.setMaximumSize(new java.awt.Dimension(68, 68));
        jlReturn.setMinimumSize(new java.awt.Dimension(68, 68));
        jlReturn.setPreferredSize(new java.awt.Dimension(68, 68));
        ImageIcon img2 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Boton de Atras.png"));
        Icon icon2 = new ImageIcon(img2.getImage().getScaledInstance(jlReturn.getWidth(), jlReturn.getHeight(), Image.SCALE_SMOOTH));
        jlReturn.setIcon(icon2);

        jlTitle.setFont(new java.awt.Font("Leelawadee UI", 1, 26)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(79, 84, 110));
        jlTitle.setText("Inventario");

        jtInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nombre", "Marca", "Tipo", "Cantidad", "Fecha caducidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtInventory);
        if (jtInventory.getColumnModel().getColumnCount() > 0) {
            jtInventory.getColumnModel().getColumn(0).setResizable(false);
            jtInventory.getColumnModel().getColumn(1).setResizable(false);
            jtInventory.getColumnModel().getColumn(2).setResizable(false);
            jtInventory.getColumnModel().getColumn(3).setResizable(false);
            jtInventory.getColumnModel().getColumn(4).setResizable(false);
            jtInventory.getColumnModel().getColumn(5).setResizable(false);
        }

        jlAddProduct.setSize(new Dimension(68,68));
        jlAddProduct.setMaximumSize(new java.awt.Dimension(68, 68));
        jlAddProduct.setMinimumSize(new java.awt.Dimension(68, 68));
        jlAddProduct.setPreferredSize(new java.awt.Dimension(68, 68));
        ImageIcon img = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Adicionar.png"));
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(jlAddProduct.getWidth(), jlAddProduct.getHeight(), Image.SCALE_SMOOTH));
        jlAddProduct.setIcon(icon);

        jlEdit.setSize(new Dimension(68,68));
        jlEdit.setMaximumSize(new java.awt.Dimension(68, 68));
        jlEdit.setMinimumSize(new java.awt.Dimension(68, 68));
        jlEdit.setPreferredSize(new java.awt.Dimension(68, 68));
        ImageIcon img3 = new ImageIcon(getClass().getResource("/documentation/Imagenes/Icono Editar.png"));
        Icon icon3 = new ImageIcon(img3.getImage().getScaledInstance(jlEdit.getWidth(), jlEdit.getHeight(), Image.SCALE_SMOOTH));
        jlEdit.setIcon(icon3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jlReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(388, 388, 388)
                        .addComponent(jlTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jlTitle)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jlAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAddProduct;
    private javax.swing.JLabel jlEdit;
    private javax.swing.JLabel jlReturn;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTable jtInventory;
    // End of variables declaration//GEN-END:variables
}
