/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.ui.registroUsr;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import lib.utils.AppColors;
import lib.ui.registroUsr.registroUsrController;

/**
 *
 * @author Fredy AGP
 */
public class registroUsr extends javax.swing.JPanel {
private AppColors color = new AppColors();
    /**
     * Creates new form registroUsr
     */
    public registroUsr() {
        initComponents();
    }

    public JLabel getAtrasButton() {
        return atrasButton;
    }

    public JTextField getCedulaTF() {
        return cedulaTF;
    }

    public JTextField getContraseñaTF() {
        return contraseñaTF;
    }

    public JTextField getDireccionTF() {
        return direccionTF;
    }

    public JTextField getEmailTF() {
        return emailTF;
    }

    public JTextField getNombreTF() {
        return nombreTF;
    }

    public JTextField getNombreUsuarioTF() {
        return nombreUsuarioTF;
    }

    public JTextField getRangoTF() {
        return rangoTF;
    }

    public JLabel getRegistrarB() {
        return registrarB;
    }

    public JLabel getRegresarB() {
        return regresarB;
    }

    public JTextField getTelefonoTF() {
        return telefonoTF;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atrasButton = new javax.swing.JLabel();
        regresarB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cedulaTF = new javax.swing.JTextField();
        nombreTF = new javax.swing.JTextField();
        telefonoTF = new javax.swing.JTextField();
        contraseñaTF = new javax.swing.JTextField();
        direccionTF = new javax.swing.JTextField();
        rangoTF = new javax.swing.JTextField();
        nombreUsuarioTF = new javax.swing.JTextField();
        registrarB = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        regresarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/Boton de Atras(2).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel2.setForeground(color.textColor());
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel3.setForeground(color.textColor());
        jLabel3.setText("Cedula:");

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel4.setForeground(color.textColor());
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel5.setForeground(color.textColor());
        jLabel5.setText("Teléfono:");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel6.setForeground(color.textColor());
        jLabel6.setText("Dirección:");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel7.setForeground(color.textColor());
        jLabel7.setText("Rol/Rango:");

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel8.setForeground(color.textColor());
        jLabel8.setText("Contraseña:");

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel9.setForeground(color.textColor());
        jLabel9.setText("Nombre de Usuario:");

        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel10.setForeground(color.textColor());
        jLabel10.setText("Registro de Usuarios");

        cedulaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTFActionPerformed(evt);
            }
        });

        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });

        telefonoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTFActionPerformed(evt);
            }
        });

        contraseñaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaTFActionPerformed(evt);
            }
        });

        direccionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTFActionPerformed(evt);
            }
        });

        rangoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangoTFActionPerformed(evt);
            }
        });

        nombreUsuarioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTFActionPerformed(evt);
            }
        });

        registrarB.setBackground(color.buttonColor());
        registrarB.setFont(new java.awt.Font("Leelawadee UI", 0, 32)); // NOI18N
        registrarB.setForeground(new java.awt.Color(255, 255, 255));
        registrarB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarB.setText("Registrar");
        registrarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarB.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarB)
                    .addComponent(atrasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(185, 185, 185)
                            .addComponent(rangoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2))
                            .addGap(197, 197, 197)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cedulaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefonoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(direccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contraseñaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreUsuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(436, 436, 436))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(atrasButton)
                .addGap(149, 667, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regresarB)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cedulaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telefonoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(direccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(rangoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreUsuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(contraseñaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registrarB)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void cedulaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaTFActionPerformed

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void telefonoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTFActionPerformed

    private void contraseñaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaTFActionPerformed

    private void direccionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTFActionPerformed

    private void rangoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangoTFActionPerformed

    private void nombreUsuarioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTFActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atrasButton;
    private javax.swing.JTextField cedulaTF;
    private javax.swing.JTextField contraseñaTF;
    private javax.swing.JTextField direccionTF;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JTextField nombreUsuarioTF;
    private javax.swing.JTextField rangoTF;
    private javax.swing.JLabel registrarB;
    private javax.swing.JLabel regresarB;
    private javax.swing.JTextField telefonoTF;
    // End of variables declaration//GEN-END:variables
}
